### ISSUE TITLE
Add gif/img demo to README

### ISSUE THREAD

**Issue by alichtman** [clbarnes/smalldataviewer#6]

**Comment by clbarnes** [comment]
I haven't tried reading gifs myself, but appreciate the point that the help text isn't necessarily as useful as a set of examples.

Were you more interested in the command line or the library use case?

**Comment by alichtman** [comment]
> Were you more interested in the command line or the library use case?

Both. I was just saying that you should show the output of the viewer at some point in the readme. Check out [stronghold](https://github.com/alichtman/stronghold) for an example of a gif demo.

People will be much more likely to use this if they know what they're getting before installing it.

**Comment by clbarnes** [comment]
Ah, good point. I'll have a think about this.

Now I'm down the image formats garden path, though, I've started on a refactor to use `imageio` which should add a lot more formats, incidentally.
